In [1]:
%run email_converter.py

Cleaned up samples_res.
Found 13 .eml files in samples to process.
Processing file 1 of 13: 13 - Phishing.eml
Processing file 2 of 13: 4.eml
Processing file 3 of 13: 7 - Safe.eml
Processing file 4 of 13: I SET THIS MESELF.eml
Processing file 5 of 13: sample-2968.eml
Processing file 6 of 13: sample-2969.eml
Processing file 7 of 13: sample-2970.eml
Processing file 8 of 13: sample-2971.eml
Processing file 9 of 13: sample-2972.eml
Processing file 10 of 13: sample-2973.eml
Processing file 11 of 13: sample-2974.eml
Processing file 12 of 13: sss.eml
Processing file 13 of 13: studio.eml
All .eml files from samples have been added to samples_res/emails-samples.mbox.
Conversion completed successfully.


In [4]:
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

%run model_train.py

Starting data preparation...
Sample data point from training set: {'html_form': <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, 'attachments': <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, 'flash_content': <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, 'html_iframe': <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, 'html_content': <tf.T

In [3]:
import warnings
warnings.filterwarnings('ignore')

%run model_predict.py

Processing file: samples_res/emails-samples.mbox
Number of emails processed: 13
Sample of loaded data:
   Unnamed: 0  html_form  attachments  flash_content  html_iframe  \
0           0      False            0          False        False   
1           1      False            0          False        False   
2           2      False            0          False        False   
3           3      False            0          False        False   
4           4      False            0          False        False   

   html_content  urls  external_resources  javascript  css  ips_in_urls  \
0         False     0                   0           0    0        False   
1         False     7                   0           0    0        False   
2         False     3                   0           0    0        False   
3         False     0                   0           0    0        False   
4         False     2                   0           0    0         True   

   at_in_urls encoding  is_phis